languageCode = 'en-us'
theme = "coming-soon"

[params]
    title = "serioli.dev" 
    description = "development that matters"
    favicon = ""
    message = "coming soon..." 
    release = "October 11, 2024" 
    background = "" 

socialIcons = [
    {name = "email", url = "info@serioli.dev"},
    {name = "github", url = "https://github.com/StuSerious"},
    {name = "linkedin", url = "https://www.linkedin.com/in/stefano-serioli-705b56159/"},
] 

[params.twitter]
	enable = false
